print("Welcome to the tip calculator.")
bill = float(input("What was the total bill? $"))
tip = int(input("What percentage tip would you like to give? 10, 12, or 15?"))
tip_percent = 1+(tip/100)
people = int(input("How many people to split the bill?"))
pay = round(bill * tip_percent / people , 2)
input(f"Each person should pay: ${pay}")
